name: Links Validator

on:
  workflow_dispatch:
  schedule:
    # run every Monday at 5 AM
    - cron: '0 5 * * 1'

jobs:
  link_checker:
    name: Link checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress --timeout 60 --max-concurrency 2 --exclude 'scoop.sh' -- './**/*.md'
          output: ./lychee/out.md
          fail: true

      - name: Get current date
        id: date
        run: echo "now=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Create issue on fail
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Automated Links Checker Report for ${{ steps.date.outputs.now }}
          content-filepath: ./lychee/out.md
          labels: links-validator
